"use client";
import { useActionState, useState } from "react";
import { Star, X } from "lucide-react";
import { createCourtReview } from "@/app/actions/reviews";

export function CourtReviewAction({ courtId, courtName }: { courtId: number; courtName: string }) {
 const [open, setOpen] = useState(false); const [state, action, pending] = useActionState(createCourtReview, undefined);
 return <><button type="button" onClick={() => setOpen(true)} className="rounded-lg border border-amber-400/50 px-3 py-1.5 text-xs font-bold text-amber-700 hover:bg-amber-50">Calificar</button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="relative w-full max-w-md rounded-2xl bg-card p-6 shadow-xl"><button onClick={() => setOpen(false)} className="absolute right-4 top-4 text-muted-foreground"><X size={20}/></button><h2 className="text-xl font-bold">¿Cómo fue {courtName}?</h2><p className="mt-2 text-sm text-muted-foreground">Tu reseña será visible para otros jugadores.</p><form action={action} className="mt-5 space-y-4"><input type="hidden" name="courtId" value={courtId}/><label className="block text-sm font-semibold">Calificación<select required name="rating" defaultValue="5" className="mt-1 block w-full rounded-lg border border-border bg-background px-3 py-2"><option value="5">★★★★★ Excelente</option><option value="4">★★★★ Muy buena</option><option value="3">★★★ Buena</option><option value="2">★★ Regular</option><option value="1">★ Mala</option></select></label><label className="block text-sm font-semibold">Comentario<textarea name="comment" maxLength={500} className="mt-1 block min-h-24 w-full rounded-lg border border-border bg-background px-3 py-2" placeholder="Cuéntanos sobre la cancha..."/></label>{state?.error && <p className="text-sm text-destructive">{state.error}</p>}{state?.success && <p className="text-sm text-emerald-600">{state.success}</p>}<button disabled={pending} className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60"><Star size={16}/>{pending ? "Enviando..." : "Publicar reseña"}</button></form></div></div>}</>;
}
