"use client";
import { useActionState, useState } from "react";
import { CalendarClock, X } from "lucide-react";
import { rescheduleBooking } from "@/app/actions/bookings";

export function RescheduleBookingAction({ bookingId, date, startTime, endTime }: { bookingId: number; date: string; startTime: string; endTime: string }) {
 const [open, setOpen] = useState(false); const [state, action, pending] = useActionState(rescheduleBooking, undefined);
 return <><button type="button" onClick={() => setOpen(true)} className="rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-bold hover:bg-secondary">Reprogramar</button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="relative w-full max-w-md rounded-2xl bg-card p-6 shadow-xl"><button onClick={() => setOpen(false)} className="absolute right-4 top-4 text-muted-foreground"><X size={20}/></button><div className="mx-auto mb-4 w-fit rounded-full bg-primary/10 p-3 text-primary"><CalendarClock size={24}/></div><h2 className="text-xl font-bold">Reprogramar reserva</h2><p className="mt-2 text-sm text-muted-foreground">El nuevo horario debe estar disponible y respetar las reglas de la cancha.</p><form action={action} className="mt-5 space-y-3"><input type="hidden" name="bookingId" value={bookingId}/><label className="block text-sm font-semibold">Nueva fecha<input required type="date" name="bookingDate" defaultValue={date} className="mt-1 block w-full rounded-lg border border-border bg-background px-3 py-2"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Inicio<input required type="time" name="startTime" defaultValue={startTime.slice(0,5)} className="mt-1 block w-full rounded-lg border border-border bg-background px-3 py-2"/></label><label className="text-sm font-semibold">Fin<input required type="time" name="endTime" defaultValue={endTime.slice(0,5)} className="mt-1 block w-full rounded-lg border border-border bg-background px-3 py-2"/></label></div>{state?.error && <p className="text-sm text-destructive">{state.error}</p>}{state?.success && <p className="text-sm text-emerald-600">{state.success}</p>}<button disabled={pending} className="w-full rounded-lg bg-primary py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60">{pending ? "Guardando..." : "Confirmar cambio"}</button></form></div></div>}</>;
}
